### ISSUE TITLE
Propose using Docker to run mysql backend

### ISSUE THREAD

**Issue by iancullinane** [politicalrev/wp.thepoliticalrev.org#1]
The following is a docker-compose.yml file which will pull and start a locally running wordpress site, complete with separate volumes for persistent data, and a local mysql database (which can easily be pre loaded with test data). This can be stood up and down without worrying about dependency management In order to ready this for dev we would need to include some improvements, like specific data containers, docker registry, and custom `Dockerfiles` to load our custom source code. For example we can modify the local dev wp image with styles, and stand up mock databases with a pre-filled dev database.

CI/CD can run the images and deploy directly. A second `docker-compose` file of the name `production.docker-compose.yml` can be generated and override with the appropriate keys and links (for example, override the database definition to point at the production db). This way we can keep logic for build and deployment terse and clear.

This is merely a proposal for how we can operate and deploy this repo easily. I am not sure of everyones docker expertise so this may not work.

```
version: '2'

services:
   db:
     image: mysql:5.7
     volumes:
       - "./.data/db:/var/lib/mysql"
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: wordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     links:
       - db
     ports:
       - "8000:80"           // go to localhost:8000 to use wordpress
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_PASSWORD: wordpress
```

**Comment by Smona** [comment]
I have a very limited knowledge of docker but if you're willing to implement this with @austinheap and write up Dev documentation it seems like a smooth Dev setup. What do you think Austin?

**Comment by austinheap** [comment]
Full support of using Docker (or any containerization that works for everyone) for dev environments. What ever gets people up and working with as little friction as possible.

There are a handful of things that we won't be able to share like the API keys used in prod. Once the base site has been ported over, we can provide people with a dataset to be loaded up too.

**Comment by iancullinane** [comment]
What about using CD/CI for things like API keys? I'm not familiar with Travis, but I know Jenkins has a plugin for injecting keys into the Jenkinsfile.

**Comment by NitroPye** [comment]
>CI/CD can run the images and deploy directly. A second docker-compose file of the name >production.docker-compose.yml can be generated and override with the appropriate keys and links >(for example, override the database definition to point at the production db). This way we can keep >logic for build and deployment terse and clear.

Compose files can inherit from one another. e.g. We can have a base.docker-compose.yml and production.docker-compose.yml only needs to override ENV vars for passwords and other production tweaks. Makes it nice and dry.

e.g. 

```
db:
  extends:
    file: base.docker-compose.yml
    service: db
  environment:
    PRODUCTION_PASSWORD_OVERRIDE: 123456 
```
